### ISSUE TITLE
is there any example using this project as an IVR

### ISSUE THREAD

**Issue by salihy** [davehorton/docker-drachtio-freeswitch-mrf#1]
Hi,

I want to use this project to develop an IVR system? Is it possible you to provide a small example about how can we do this?

**Comment by davehorton** [comment]
here is a very simple example showing how to connect to a media server and play a prompt

**Comment by salihy** [comment]
I have 2 questions,
1. where should be sound file located at? (app server or freepbx container)
2. How can I implement a queue using drachtio-fsmrf?

**Comment by davehorton** [comment]
If you provide a relative path (as that example does) it will look under whatever the freeswitch sounds directory is configured to be (/usr/local/freeswitch/sounds by default).  You can also use an absolute path.

When you say "queue" what exactly do you mean (freeswitch has a concept of queues for example, but I am pretty sure it is not what you are referring to)

**Comment by salihy** [comment]
I was referring to freeswitch queues but after considering again, I might not need. Thanks.

**Comment by davehorton** [comment]
you could use the [Endpoint#api](http://davehorton.github.io/drachtio-fsmrf/api/Endpoint.html#api) to call any arbitrary freeswitch api, including supporting queues

**Comment by salihy** [comment]
Thank you
