### ISSUE TITLE
docker-drachtio-freeswitch-mrf with docker-compose

### ISSUE THREAD

**Issue by alorka** [davehorton/docker-drachtio-freeswitch-mrf#6]
Hello Dave, 

I couldn't figure out how to use the docker image with docker-compose to allow configuring the following:

--sip-port the sip port to listen on (default: 5080)
--tls-port the tls port to listen on (default: 5081)
--event-socket-port the port that Freeswitch event socket listens on (default: 8021)
--password the event socket password (default: ClueCon)
--rtp-range-start the starting UDP port for RTP traffic
--rtp-range-end the ending UDP port for RTP traffic

Thank you.

**Comment by alorka** [comment]
Using Dockerfile and building a new image for the time being .. thanks.

**Comment by davehorton** [comment]
there are options in the entrypoint.sh for what you want to do.  Since you did not describe the results of what you tried, I cannot give specific help.  But I would suggest looking at the that file

**Comment by alorka** [comment]
I added environment variables to a Dockerfile and edited the entrypoint.sh then built a new image which solved my  issue with docker-compose file. 

Thanks a lot Dave.

**Comment by davehorton** [comment]
You never gave me sufficient information in this issue about the exact problem you experienced to actually make any fixes, if necessary, to the project.  That's disappointing.

**Comment by alorka** [comment]
My bad; I am a beginner and still figuring things out. I surely do not want to be disappointing. 

There is no issue; it was more of a feature request or guidance on how to set the docker run arguments via docker compose file. I had no idea how it worked and figured it out during the last couple of days.

I created a pull request to include Freeswitch configuration support to docker compose file as environment variables.  

Thanks.

**Comment by davehorton** [comment]
Thanks, that's great!  I will review the PR

**Comment by alorka** [comment]
I assumed you are going to build a new docker image and that image is pushed to docker hub. 

Let me know if you would like me to modify the docker compose example to include a build context rather than a reference to the updated docker hub image.
